# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iGen' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iGen
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'

  target 'iGenTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iGenUITests' do
    inherit! :search_paths
    # Pods for testing

  end

end
